### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by clayellis** [registerbyu/registerbyu#3]
Hey contributors—just curious, what ever happened to registerbyu.com? Did BYU shut it down?

**Comment by nhumrich** [comment]
This project has been an ongoing senior project, and every year a new set of students pick it up. This year, no one picked it up, leaving me (no longer a student), to pay for and maintain the site, something which I dont have much time for.  The site wasnt getting very much traffic this semester, so I decided to shut it down due to little interest.
If you are interested in the site, I am willing to put the site back up given there is someone willing to maintain the code and run the scripts to get the new data.
